"""add base structure

Revision ID: fcca6643ce26
Revises:
Create Date: 2017-12-06 17:38:58.728073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcca6643ce26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bible_bibles',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('abreviation', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('fuente', sa.String(length=50), nullable=True),
    sa.Column('apocrifa', sa.Integer(), nullable=True),
    sa.Column('fuertes', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('bible_books',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('testament', sa.String(length=1), nullable=False),
    sa.Column('chapters', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('bible_books_chapters',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('idBook', sa.Integer(), nullable=True),
    sa.Column('chapter', sa.Integer(), nullable=False),
    sa.Column('verses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idBook'], [u'bible_books._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    op.create_table('bible_verses',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('idBible', sa.Integer(), nullable=True),
    sa.Column('idChapter', sa.Integer(), nullable=True),
    sa.Column('verse', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=1024), nullable=False),
    sa.ForeignKeyConstraint(['idChapter'], [u'bible_books_chapters._id'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bible_verses')
    op.drop_table('bible_books_chapters')
    op.drop_table('bible_books')
    op.drop_table('bible_bibles')
    # ### end Alembic commands ###
